### PR TITLE
bosh_parameter

### PR DESCRIPTION
**Pull request by cobrowserAlex**
This PR exposes the BOSH connection parameters so an arbiraty web client can manage the connection properly

### CODE REVIEW

**Comment by cobrowserAlex** [comment]
This will be a mess, I'll rebase on this master

**Comment by piotr-cz** [comment]
Hold on, I was going to make a PR here with all the diff commits made in my repo and you involuntarily just did that.
I suggest renaming this PR to something 'Pack of commits form piotr-cz/xmpp-prebind-php' and see what authors think about it.

**Comment by cobrowserAlex** [comment]
Yes, involuntarily. Jetbrains IDEs have some amazing features, but you gotta watch out which buttons to press. I'll leave you to this. And wait. After you've done the PR, I will change the Composer URI.

**Comment by piotr-cz** [comment]
it's now included in https://github.com/candy-chat/xmpp-prebind-php/pull/11

**Pull request closed without merging**
